package com.scraper;

public enum Dynasty {
    DINASTIA_GIULIO_CLAUDIA,
    GUERRA_CIVILE_ROMANA,
    DINASTIA_DEI_FLAVI,
    IMPERATORI_ADOTTIVI,
    GUERRA_CIVILE_ROMANA2,
    DINASTIA_DEI_SEVERI,
    ANARCHIA_MILITARE,
    DINASTIA_VALERIANA,
    IMPERATORI_ILLIRICI,
    RIFORMA_TETRARCHICA,
    GUERRA_CIVILE_ROMANA_3,
    DINASTIA_COSTANTINIANA,
    CASATA_VALENTINIANO_TEODOSIO,
    CASATA_TEODOSIO,
    ULTIMI_IMPERATORI;

    public int getValue(){
        return ordinal() + 4;   //  Starting from the 4th table of the page
    }
}
